version: "3.7"

services:
  data-reco:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEBIAN_FRONTEND=noninteractive
      

    image: "data-recommendation:latest"
    environment: 
      CONFIG_ID: ${CONFIG_ID}
    network_mode: "host"
    container_name: datareco
    privileged: true
    #restart: on-failure

    volumes:
      - ./docker_vols/model_logs:/data-recommend/model_logs
      - ./docker_vols/data/recomm_data/honda:/data-recommend/data
      - ./docker_vols/data/recomm_data/honda_op:/data-recommend/output
      - .scripts:/data-recommend/scripts
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

    working_dir: /data-recommend/scripts
    command: python3 main.py
